services:
  - type: web
    name: donations-app
    env: node
    plan: free
    buildCommand: docker build -t donations-app .
    startCommand: docker run -p 8080:8080 donations-app
    envVars:
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_CLIENT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
